'use client'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/nav/Header";
import Sidebar from "@/components/nav/Sidebar";
import { usePathname } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

//export const metadata: Metadata = {
  //title: "Create Next App",
  //description: "Generated by create next app",
//};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const showNav = pathname !== "/auth/login" && pathname !== "/auth/register";

  return (
    <html lang="en">
      <body>
        {showNav && <Header />}
        <div className="flex h-screen border-collapse overflow-hidden">
          {showNav && <Sidebar />}

          <main
            className={`${inter.className} flex-1 overflow-y-auto overflow-x-hidden pt-16 bg-secondary/10 pb-1`}
          >
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
